version: '3'
services:
  mongodb:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=ndungu
    #   - MONGO_INITDB_ROOT_PASSWORD=ndungu11
    volumes:
      - mongod:/data/db
      - bypass-mongodb_data:/data/db
  store_api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongod:
  bypass-mongodb_data: